[build]
  base = "to-do-list/client"  
  publish = "to-do-list/client/build"  
  command = "yarn build"  

[build.environment]
  NODE_VERSION = "16"  

[context.production.environment]
  REACT_APP_BACKEND_URL = "https://to-do-list-4iee.onrender.com"  
