[build]
  base = "client"                
  publish = "client/build"       
  command = "yarn build"         

[build.environment]
  NODE_VERSION = "18"            

[context.production.environment]
  REACT_APP_BACKEND_URL = "https://to-do-list-4iee.onrender.com"  

[functions]
  directory = "client/functions"
  node_bundler = "esbuild"